wordpress:
  image:
    repository: wordpress
    tag: latest
    pullPolicy: IfNotPresent
  
  persistence:
    enabled: true
    size: 10Gi
    
  service:
    type: NodePort
    port: 80
    nodePort: 32000

mysql:
  image:
    repository: mysql
    tag: 5.7
    pullPolicy: IfNotPresent
    
  persistence:
    enabled: true
    size: 8Gi
    
  env:
    MYSQL_ROOT_PASSWORD: wordpress-pass
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress-pass
