apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.mariadb.image }}
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: {{ .Values.mariadb.mariadbRootPassword }}
            - name: MARIADB_DATABASE
              value: {{ .Values.mariadb.mariadbDatabase }}
            - name: MARIADB_USER
              value: {{ .Values.mariadb.mariadbUser }}
            - name: MARIADB_PASSWORD
              value: {{ .Values.mariadb.mariadbPassword }}
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: {{ .Values.mariadb.storage.pvc.name }}