apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.wordpress.storage.pv.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.wordpress.storage.pv.storageClassName }}
  capacity:
    storage: {{ .Values.wordpress.storage.size }}
  accessModes:
    - {{ .Values.wordpress.storage.accessMode }}
  hostPath:
    path: {{ .Values.wordpress.storage.pv.hostPath }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mariadb.storage.pv.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.mariadb.storage.pv.storageClassName }}
  capacity:
    storage: {{ .Values.mariadb.storage.size }}
  accessModes:
    - {{ .Values.mariadb.storage.accessMode }}
  hostPath:
    path: {{ .Values.mariadb.storage.pv.hostPath }}