apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: wordpress-server
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.wordpress.service.nodePort }}

