apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        securityContext:
          runAsUser: 0
        command: ["sh", "-c", "mkdir -p /mnt/data/wordpress && chmod 777 /mnt/data/wordpress"]
        volumeMounts:
        - name: host-path
          mountPath: /mnt/data
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress-pass
        - name: WORDPRESS_DB_NAME
          value: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
      - name: host-path
        hostPath:
          path: /mnt/data
