apiVersion: rbac.authorization.k8s.io/v1
kind: Role  # Changed from ClusterRole
metadata:
  name: jenkins
  namespace: {{ .Values.namespace }} # Role is now namespace-scoped
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets", "configmaps"] # More specific permissions
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]