apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding  # Changed from ClusterRoleBinding
metadata:
  name: jenkins
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: jenkins # Service account name
  namespace: {{ .Values.namespace }} # MUST be in the same namespace as Role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role  # Refer to the Role, not ClusterRole
  name: jenkins