apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
  namespace: jenkins  # Important: Specify the namespace here
subjects:
- kind: ServiceAccount
  name: jenkins # Directly use "jenkins" if the service account is named "jenkins"
  # Remove the templating if not needed: namespace: {{ .Values.namespace }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-role