apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins  # Important: Specify the namespace here
  name: jenkins-role
rules:
  - apiGroups: ["apps", "extensions", ""] # Include "" for core API resources like services
    resources: ["deployments", "replicasets", "pods", "services", "configmaps", "secrets", "serviceaccounts"] # List all resources Jenkins needs
    verbs: ["*"] # Or specify more restrictive verbs if possible: ["get", "list", "watch", "create", "update", "patch", "delete"]