name: Deploy Terraform Infrastructure

on:
  push:
    branches:
      - main
      - task_2
  pull_request:
    branches:
      - main
      - task_2

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Check Terraform format
        run: terraform fmt -check
      
      - name: Validate Terraform files
        run: terraform validate

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        continue-on-error: true

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve